# Generated by Django 4.1.3 on 2022-11-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_entry', models.DateTimeField(auto_now_add=True)),
                ('vibe', models.CharField(choices=[(1, 'Chill: 5 - 10 People'), (2, 'Party: 20 - 30 People'), (3, 'Rager: 50+ People')], default=1, max_length=50, null=True)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='venue.venue')),
            ],
        ),
    ]
