# Generated by Django 4.1.3 on 2022-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='first_entry',
            field=models.DateTimeField(),
        ),
    ]
