# Generated by Django 4.1.3 on 2022-12-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='party',
        ),
    ]
