"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-i!0(gmwm9jpd3c1bocjuwk_&fl5cly)q_h!m)wbo=xbt$gz!2l'
SECRET_KEY = 'giyBtGiAiTKpsRxgNasNhDOCCglcPTxUGYJcmppgZzqgMujZAn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'realm-dj-34ezrkuhla-ew.a.run.app',
    'localhost:8080',
    'localhost:4000',
    'localhost:5000',
    'effb-82-0-186-223.eu.ngrok.io',
    'kubernetes.docker.internal', 'localhost:8000', "http://localhost:3000",
                 "exp://10.40.195.102:19000",
                 "http://localhost:19002",
                 "http://localhost:19000",
                 "http://localhost:8000", "localhost", 'localhost']


# Application definition

INSTALLED_APPS = [
    # 3rd Party Apps
    'rest_framework',
    'jwt',

    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 1st Party/My Apps
    'base',
    'user',
    'party',
    'invite'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'base.urls'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = [
    "exp://10.40.195.102:19000",
    'http://localhost:19002'
    'http://localhost:19000',
    'http://localhost:8000',
    "https://mydeployedapplication.com",
    'http://192.168.0.17:19000',
    'exp://192.168.0.17:19000',
    'http://localhost:3000',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "exp://10.40.195.102:19000",
    "http://localhost:19002",
    "http://localhost:19000", 
    "http://localhost:8000",
    "exp://192.168.0.17:19000",
]

CSRF_COOKIE_NAME = "csrftoken"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'realm_django'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASS', 'blueLilacs8830'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        # This PORT needs to be the SAME as the the one the cloud sql auth proxy is run on
        'PORT': os.environ.get('DB_PORT', '8000'),
    }
    # Use django-environ to parse the connection string
    # "default": env.db()
}
# If the flag as been set, configure to use proxy
# if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
#     DATABASES["default"]["HOST"] = "127.0.0.1"
#     DATABASES["default"]["PORT"] = 5432

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.AllowAny',
    # ],
    # JWTAuthentication added to each relevant view
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.JWTAuthentication'
    ]
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.CustomUser'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

CORS_ALLOWED_ORIGINS = [
    "https://realm-dj-34ezrkuhla-ew.a.run.app",
    "http://localhost:8000",
    "exp://10.40.195.102:19000",
    "http://localhost:19002",
    "http://192.168.0.17:19000",
    "exp://192.168.0.17:19000",
    "http://localhost:19000",
]

CSRF_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SECURE = False

# Configuration for Image Uploads
MEDIA_URL = '/profile_pictures/' # URL used to access file over HTTP
MEDIA_ROOT = os.path.join(BASE_DIR, 'profiles_pictures')