# Generated by Django 4.1.3 on 2022-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[(1, 'Arts/Humanities'), (2, 'Business'), (3, 'Dentistry'), (4, 'Engineering'), (5, 'Law'), (6, 'Medic/Life Sciences'), (7, 'Natural Sciences'), (8, 'Nursing'), (9, 'Pysch/Neuroscience'), (10, 'Social Science')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
