# Generated by Django 4.1.3 on 2022-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.IntegerField(choices=[(1, 'Arts/Humanities'), (2, 'Business'), (3, 'Dentistry'), (4, 'Engineering'), (5, 'Law'), (6, 'Medic/Life Sciences'), (7, 'Natural Sciences'), (8, 'Nursing'), (9, 'Pysch/Neuroscience'), (10, 'Social Science')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Host')], default=0),
        ),
    ]
