# Generated by Django 4.1.3 on 2022-12-13 15:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/profile_pictures'), upload_to=''),
        ),
    ]
