# Generated by Django 4.1.3 on 2022-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
