# Generated by Django 4.1.3 on 2022-12-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
