# Generated by Django 4.1.3 on 2023-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_birthdate_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateTimeField(blank=True, default='\x16\x162002-09-10 01:00:00.000 +0100'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
            preserve_default=False,
        ),
    ]
