# Generated by Django 4.1.3 on 2023-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_birthdate_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
    ]
