# Generated by Django 4.1.3 on 2023-02-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Arts/Humanities'), (2, 'Business'), (3, 'Dentistry'), (4, 'Engineering'), (5, 'Law'), (6, 'Medic/Life Sciences'), (7, 'Natural Sciences'), (8, 'Nursing'), (9, 'Pysch/Neuroscience'), (10, 'Social Science')], null=True),
        ),
    ]
