# Generated by Django 4.1.3 on 2023-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
