# Generated by Django 4.1.3 on 2023-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
    ]
